services:
  - type: web
    name: rag-llm-backend
    runtime: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false

